import { PettyCashCategory } from '@/core/domain/enums';
import { DomainError } from '@/core/errors';

export interface PettyCashAssessmentProps {
    id?: string;
    fund_id: string;
    period: string;                         // 'YYYY-MM'
    description: string;
    category?: PettyCashCategory | null;
    total_amount: number;                   // > 0
    created_by: string;
    created_at?: Date;
    /**
     * Slice B: assessment kind.
     *   GENERAL — normal proration across units (default).
     *   EXPRESS — rapid one-shot linked to a specific expense entry.
     */
    kind?: 'GENERAL' | 'EXPRESS';
    /**
     * Slice B: for EXPRESS assessments, the petty_cash_entries.id of the
     * expense that triggered this assessment. NULL for GENERAL.
     */
    source_entry_id?: string | null;
}

/**
 * An assessment "batch" — one named prorrateo. Multiple batches per
 * period are supported and expected (ascensor, agua, mantenimiento …).
 *
 * The invoices generated by a batch carry `invoices.assessment_id =
 * this.id` so they can be aggregated per-batch in the transparency view.
 */
export class PettyCashAssessment {
    private static readonly PERIOD_RE = /^\d{4}-\d{2}$/;

    constructor(private props: PettyCashAssessmentProps) {
        if (!props.fund_id) {
            throw new DomainError('fund_id is required', 'VALIDATION_ERROR', 400);
        }
        if (!PettyCashAssessment.PERIOD_RE.test(props.period ?? '')) {
            throw new DomainError(
                'period must be in YYYY-MM format',
                'VALIDATION_ERROR',
                400
            );
        }
        if (!props.description?.trim()) {
            throw new DomainError(
                'Assessment description is required',
                'VALIDATION_ERROR',
                400
            );
        }
        if (!(props.total_amount > 0)) {
            throw new DomainError(
                'Assessment total_amount must be greater than zero',
                'VALIDATION_ERROR',
                400
            );
        }
        if (!props.created_by) {
            throw new DomainError('created_by is required', 'VALIDATION_ERROR', 400);
        }

        if (!props.created_at) {
            this.props.created_at = new Date();
        }
    }

    get id(): string | undefined { return this.props.id; }
    get fund_id(): string { return this.props.fund_id; }
    get period(): string { return this.props.period; }
    get description(): string { return this.props.description; }
    get category(): PettyCashCategory | null | undefined { return this.props.category; }
    get total_amount(): number { return this.props.total_amount; }
    get created_by(): string { return this.props.created_by; }
    get created_at(): Date { return this.props.created_at!; }
    get kind(): 'GENERAL' | 'EXPRESS' { return this.props.kind ?? 'GENERAL'; }
    get source_entry_id(): string | null { return this.props.source_entry_id ?? null; }

    toJSON() {
        return {
            id: this.props.id,
            fund_id: this.props.fund_id,
            period: this.props.period,
            description: this.props.description,
            category: this.props.category ?? null,
            total_amount: this.props.total_amount,
            created_by: this.props.created_by,
            created_at: this.props.created_at,
            kind: this.kind,
            source_entry_id: this.source_entry_id,
        };
    }
}
