import { IPaymentRepository } from '../../domain/repository';
import { IInvoiceRepository, IPaymentAllocationRepository, ICreditLedgerRepository } from '@/modules/billing/domain/repository';
import { NotFoundError, ForbiddenError } from '@/core/errors';
import { CreditLedgerEntry, CreditLedgerReferenceType } from '@/modules/billing/domain/entities/CreditLedgerEntry';
import { InvoiceStatus } from '@/modules/billing/domain/entities/Invoice';
import {
    PaymentStatus,
    InvoiceTag,
    PettyCashEntryType,
    PettyCashEntryReferenceType,
} from '@/core/domain/enums';
import { PettyCashRepository } from '@/modules/petty-cash/domain/repositories/PettyCashRepository';
import { PettyCashEntry } from '@/modules/petty-cash/domain/entities/PettyCashEntry';

export interface ReversePaymentDTO {
    paymentId: string;
    requesterId: string; // Admin only
    reason: string;
}

// SECURITY: this use case does NOT perform its own role / building-access
// check. Authorization is gated at the route layer via requireRole
// ([ADMIN, BOARD]). See src/modules/payments/presentation/routes.ts
// (paymentAdminRoutes). If you ever mount this use case from a new
// entry point, apply the same guard there or add an internal check
// (see ApprovePayment.ts for the building-membership pattern).
export class ReversePayment {
    constructor(
        private paymentRepo: IPaymentRepository,
        private invoiceRepo: IInvoiceRepository,
        private allocationRepo: IPaymentAllocationRepository,
        private creditLedgerRepo: ICreditLedgerRepository,
        private pettyCashRepo: PettyCashRepository
    ) { }

    async execute(dto: ReversePaymentDTO): Promise<void> {
        const payment = await this.paymentRepo.findById(dto.paymentId);
        if (!payment) {
            throw new NotFoundError(`Payment ${dto.paymentId} not found`);
        }

        if (payment.status !== PaymentStatus.APPROVED) {
            throw new ForbiddenError('Only approved payments can be reversed');
        }

        // 1. Mark payment as REJECTED with a REVERSED note.
        payment.reject(dto.requesterId, `REVERSED: ${dto.reason}`);
        await this.paymentRepo.update(payment);

        // 2. Reverse credit entries generated by the original payment.
        //    Filter explicitly by PAYMENT reference_type so we never try to
        //    "reverse a reversal" if this method runs twice against the same
        //    paymentId (the APPROVED guard above already blocks that, but
        //    the filter makes the intent explicit).
        const entries = await this.creditLedgerRepo.findByReferenceId(dto.paymentId);
        for (const entry of entries) {
            if (entry.isCredit && entry.reference_type === CreditLedgerReferenceType.PAYMENT) {
                const reversalEntry = CreditLedgerEntry.reversalOf(
                    entry,
                    `Reversión de pago ${dto.paymentId}: ${dto.reason}`
                );
                await this.creditLedgerRepo.deductCredit(reversalEntry);
            }
        }

        // 3. Subtract the applied amount from each affected invoice, then
        //    delete the allocation. The domain now owns paid_amount /
        //    status recalculation (triggers dropped in 20260412091500).
        //    While we're here, if the invoice was a PETTY_CASH unit-level
        //    one, reverse the auto-collection entry in the fund ledger so
        //    the building's petty-cash balance un-reflects the collection.
        const allocations = await this.allocationRepo.findByPaymentId(dto.paymentId);
        for (const alloc of allocations) {
            const invoice = await this.invoiceRepo.findById(alloc.invoice_id);
            if (invoice && invoice.status !== InvoiceStatus.CANCELLED) {
                invoice.subtractPayment(alloc.amount);
                invoice.updateStatus();
                await this.invoiceRepo.update(invoice);
            }
            if (invoice) {
                await this.reversePettyCashCollectionIfApplicable(
                    invoice,
                    dto.paymentId,
                    dto.requesterId,
                    dto.reason
                );
            }
            await this.allocationRepo.delete(alloc.id);
        }
    }

    /**
     * Counter-asiento in petty_cash_entries for any collection entry
     * that ApprovePayment generated for this (invoice, payment) pair.
     * Mirrors how credit ledger entries are reversed above.
     */
    private async reversePettyCashCollectionIfApplicable(
        invoice: { id: string; tag: InvoiceTag; unit_id?: string; building_id?: string },
        paymentId: string,
        requesterId: string,
        reason: string
    ): Promise<void> {
        if (invoice.tag !== InvoiceTag.PETTY_CASH) return;
        if (!invoice.unit_id) return;
        if (!invoice.building_id) return;

        const existing = await this.pettyCashRepo.findEntriesByReference(
            PettyCashEntryReferenceType.INVOICE_PAYMENT,
            invoice.id
        );
        const collectionForThisPayment = existing.find(
            e => e.type === PettyCashEntryType.COLLECTION &&
                 e.description.includes(paymentId)
        );
        if (!collectionForThisPayment) return;

        // Skip if already reversed.
        const alreadyReversed = existing.some(
            e => e.type === PettyCashEntryType.REVERSAL &&
                 e.reference_id === collectionForThisPayment.id
        );
        if (alreadyReversed) return;

        const counter = PettyCashEntry.reversalOf(collectionForThisPayment, {
            description: `Reversión de cobro por pago ${paymentId}: ${reason}`,
            createdBy: requesterId,
        });
        await this.pettyCashRepo.addEntry(counter);
    }
}
